-- MySQL Script generated by MySQL Workbench
-- Tue Mar 18 11:47:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema portfolio_heatmap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio_heatmap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio_heatmap` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `portfolio_heatmap` ;

-- -----------------------------------------------------
-- Table `portfolio_heatmap`.`historical_prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_heatmap`.`historical_prices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ticker` VARCHAR(10) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `closing_price` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ticker` (`ticker` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 99
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `portfolio_heatmap`.`portfolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_heatmap`.`portfolio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ticker` VARCHAR(10) NULL DEFAULT NULL,
  `total_shares` INT NULL DEFAULT NULL,
  `cost_basis` DECIMAL(12,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ticker` (`ticker` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `portfolio_heatmap`.`stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_heatmap`.`stocks` (
  `ticker` VARCHAR(255) NOT NULL,
  `company_name` VARCHAR(255) NULL DEFAULT NULL,
  `sector` VARCHAR(255) NULL DEFAULT NULL,
  `market_cap` BIGINT NOT NULL,
  `pe_ratio` DOUBLE NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`ticker`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
